---
abstract: unknown
author:
  - 'Aaron Trevena <teejay@(none)>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-HTTP-Response
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Response: 0
resources:
  repository: https://github.com/hashbangperl/Test--HTTP--Response
version: 0.05
